#!/bin/sh
while true;do 
  if [ -f error.lock ]; then
    echo "error.lock is present, i will not continue"
    exit 1
  fi
  bin/auths.sh;
  bin/getinventory.sh;
  cp ../config.war.inc config.inc;
  bin/randomizemap.sh maps/vilnius.txt;
  bin/hacknkillnup.sh map.war.txt ;
  sleep 600;
done
