#!/usr/bin/perl
#use strict;
use JSON::XS;
use Encode;
use Unicode::Escape qw(escape unescape);
my $knobsyncts=`cat knobsyncts.txt|tr -d "\r\n"`;
my $HEXLATE6=$ARGV[0];
my $HEXLONE6=$ARGV[1];
my $MESSAGE=$ARGV[2];
binmode(STDOUT, ":utf8");
my %request;
my $request=\%request;
my $false=false;
my $MESSAGE = escape($ARGV[2]);
$request->{params}{factionOnly}=$false;
$request->{params}{message}="$MESSAGE";
$request->{params}{playerLocation}="$HEXLATE6,$HEXLONE6";
my $json_string    = encode_json($request);
print $json_string;
close(FILE);
